using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace HActLib
{
    public enum ConditionType : uint
    {
        dmy = 0x0,
        random = 0x1,
        scenario_timeline_results = 0x2,
        play_count = 0x3,
        program_param = 0x4,
        distance = 0x5,
        pad_button = 0x6,
        shop_trade_item = 0x7,
        loop_count = 0x8,
        page_end = 0x9,
        select_menu = 0xA,
        battle = 0xB,
        ai_finish = 0xC,
        clock_pkg = 0xD,
        mg_caba_tension = 0xE,
        hact_condition_flag = 0xF,
        player_point = 0x10,
        ui_finish = 0x11,
        no_speech = 0x12,
        scenario_timeline_clock_range = 0x13,
        finish_tww = 0x14,
        item_giving = 0x15,
        skip = 0x16,
        mg_caba_rank = 0x17,
        item_have = 0x18,
        page_play_count = 0x19,
        finish_reward = 0x1A,
        special_favor = 0x1B,
        tgs = 0x1C,
        not_download_chunk = 0x1D,
        taxi_select = 0x1E,
        stage_warp = 0x1F,
        playing_drama_talk = 0x20,
        drunk_level = 0x21,
        talk_text_end = 0x22,
        mg_toylets = 0x23,
        unlocking = 0x24,
        mg_snack = 0x25,
        enemy_num = 0x26,
        talk_flag = 0x27,
        talk_value = 0x28,
        player_move = 0x29,
        evidence_choice = 0x2A,
        shop = 0x2B,
        select_survey_point = 0x2C,
        unopened_survey_point_count = 0x2D,
        language = 0x2E,
        daynight = 0x2F,
        verification_interrupted = 0x30,
        checked_survey_point = 0x31,
        player_skill = 0x32,
        took_picture_in_photo_mission = 0x33,
        range = 0x34,
        camera_photo_mode = 0x35,
        album_space = 0x36,
        speech_skip_end = 0x37,
        exclusion_permission = 0x38,
        player_gauge = 0x39,
        player_stand = 0x3A,
        camera_photo_label = 0x3B,
        added_shop_player_point = 0x3C,
        planter_state = 0x3D,
        non_human = 0x3E,
        part_time_job_quest_clear = 0x3F,
        party_num = 0x40,
        cabaret_yoasobi = 0x41,
        player_personality_lv = 0x42,
        sujimon_complete = 0x43,
        restaurant = 0x44,
        quest_cleared = 0x45,
        boss = 0x46,
        trial = 0x47,
        tgs_or_trial = 0x48,
        trust_level = 0x49,
        damage_reaction = 0x4A,
        has_cd = 0x4B,
        equip_armor = 0x4C,
    };
}
