using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace HActLib
{
    public enum HActReplaceID : uint
    {
        invalid,         // constant 0x0
        hu_player,       // constant 0x1
        hu_uid,      // constant 0x2
        hu_enemy_00,         // constant 0x3
        hu_enemy_01,         // constant 0x4
        hu_enemy_02,         // constant 0x5
        hu_enemy_03,         // constant 0x6
        hu_enemy_04,         // constant 0x7
        hu_enemy_05,         // constant 0x8
        hu_enemy_06,         // constant 0x9
        hu_enemy_07,         // constant 0xA
        hu_enemy_08,         // constant 0xB
        hu_enemy_09,         // constant 0xC
        hu_npc_00,       // constant 0xD
        hu_npc_01,       // constant 0xE
        hu_npc_02,       // constant 0xF
        hu_npc_03,       // constant 0x10
        hu_npc_04,       // constant 0x11
        hu_npc_05,       // constant 0x12
        hu_npc_06,       // constant 0x13
        hu_npc_07,       // constant 0x14
        hu_npc_08,       // constant 0x15
        hu_npc_09,       // constant 0x16
        hu_tag,      // constant 0x17
        hu_enemy_10,         // constant 0x18
        hu_enemy_11,         // constant 0x19
        hu_enemy_12,         // constant 0x1A
        hu_enemy_13,         // constant 0x1B
        hu_enemy_14,         // constant 0x1C
        hu_enemy_15,         // constant 0x1D
        hu_enemy_16,         // constant 0x1E
        hu_enemy_17,         // constant 0x1F
        hu_enemy_18,         // constant 0x20
        hu_enemy_19,         // constant 0x21
        hu_enemy_20,         // constant 0x22
        hu_enemy_21,         // constant 0x23
        hu_enemy_22,         // constant 0x24
        hu_enemy_23,         // constant 0x25
        hu_enemy_24,         // constant 0x26
        hu_enemy_25,         // constant 0x27
        hu_enemy_26,         // constant 0x28
        hu_enemy_27,         // constant 0x29
        hu_enemy_28,         // constant 0x2A
        hu_enemy_29,         // constant 0x2B
        hu_enemy_30,         // constant 0x2C
        hu_enemy_31,         // constant 0x2D
        hu_npc_10,       // constant 0x2E
        hu_npc_11,       // constant 0x2F
        hu_npc_12,       // constant 0x30
        hu_npc_13,       // constant 0x31
        hu_npc_14,       // constant 0x32
        hu_npc_15,       // constant 0x33
        hu_npc_16,       // constant 0x34
        hu_npc_17,       // constant 0x35
        hu_npc_18,       // constant 0x36
        hu_npc_19,       // constant 0x37
        hu_npc_20,       // constant 0x38
        hu_npc_21,       // constant 0x39
        hu_npc_22,       // constant 0x3A
        hu_npc_23,       // constant 0x3B
        hu_npc_24,       // constant 0x3C
        hu_npc_25,       // constant 0x3D
        hu_npc_26,       // constant 0x3E
        hu_npc_27,       // constant 0x3F
        hu_npc_28,       // constant 0x40
        hu_npc_29,       // constant 0x41
        hu_npc_30,       // constant 0x42
        hu_npc_31,       // constant 0x43
        hu_stalker_00,       // constant 0x44
        hu_stalker_01,       // constant 0x45
        hu_stalker_02,       // constant 0x46
        hu_stalker_03,       // constant 0x47
        hu_stalker_04,       // constant 0x48
        hu_stalker_05,       // constant 0x49
        hu_stalker_06,       // constant 0x4A
        hu_stalker_07,       // constant 0x4B
        hu_stalker_08,       // constant 0x4C
        hu_stalker_09,       // constant 0x4D
        hu_stalker_10,       // constant 0x4E
        hu_stalker_11,       // constant 0x4F
        hu_stalker_12,       // constant 0x50
        hu_stalker_13,       // constant 0x51
        hu_stalker_14,       // constant 0x52
        hu_stalker_15,       // constant 0x53
        hu_stalker_16,       // constant 0x54
        hu_stalker_17,       // constant 0x55
        hu_stalker_18,       // constant 0x56
        hu_stalker_19,       // constant 0x57
        hu_stalker_20,       // constant 0x58
        hu_stalker_21,       // constant 0x59
        hu_stalker_22,       // constant 0x5A
        hu_stalker_23,       // constant 0x5B
        hu_stalker_24,       // constant 0x5C
        hu_stalker_25,       // constant 0x5D
        hu_stalker_26,       // constant 0x5E
        hu_stalker_27,       // constant 0x5F
        hu_stalker_28,       // constant 0x60
        hu_stalker_29,       // constant 0x61
        hu_stalker_30,       // constant 0x62
        hu_stalker_31,       // constant 0x63
        hu_last_enemy_00,        // constant 0x64
        hu_stalker_man_00,       // constant 0x65
        hu_stalker_woman_00,         // constant 0x66
        after_replace,       // constant 0x67
        prev_player_model,       // constant 0x68
        now_player_model,        // constant 0x69
        hu_enemy_not_human_00,       // constant 0x6A
        hu_enemy_not_human_01,       // constant 0x6B
        hu_enemy_not_human_02,       // constant 0x6C
        hu_enemy_not_human_03,       // constant 0x6D
        hu_enemy_not_human_04,       // constant 0x6E
        hu_enemy_not_human_05,       // constant 0x6F
        hu_enemy_not_human_06,       // constant 0x70
        hu_enemy_not_human_07,       // constant 0x71
        hu_enemy_not_human_08,       // constant 0x72
        hu_enemy_not_human_09,       // constant 0x73
        hu_enemy_not_human_10,       // constant 0x74
        hu_enemy_not_human_11,       // constant 0x75
        hu_enemy_not_human_12,       // constant 0x76
        hu_enemy_not_human_13,       // constant 0x77
        hu_enemy_not_human_14,       // constant 0x78
        hu_enemy_not_human_15,       // constant 0x79
        hu_enemy_not_human_16,       // constant 0x7A
        hu_enemy_not_human_17,       // constant 0x7B
        hu_enemy_not_human_18,       // constant 0x7C
        hu_enemy_not_human_19,       // constant 0x7D
        hu_enemy_not_human_20,       // constant 0x7E
        hu_enemy_not_human_21,       // constant 0x7F
        hu_enemy_not_human_22,       // constant 0x80
        hu_enemy_not_human_23,       // constant 0x81
        hu_enemy_not_human_24,       // constant 0x82
        hu_enemy_not_human_25,       // constant 0x83
        hu_enemy_not_human_26,       // constant 0x84
        hu_enemy_not_human_27,       // constant 0x85
        hu_enemy_not_human_28,       // constant 0x86
        hu_enemy_not_human_29,       // constant 0x87
        hu_enemy_not_human_30,       // constant 0x88
        hu_enemy_not_human_31,       // constant 0x89
        hu_player1,      // constant 0x8A
        hu_player2,      // constant 0x8B
        hu_player3,      // constant 0x8C
        hu_player4,      // constant 0x8D
        hu_nakama_00,        // constant 0x8E
        hu_nakama_01,        // constant 0x8F
        hu_nakama_02,        // constant 0x90
        hu_nakama_03,        // constant 0x91
        talker,      // constant 0x92
        quest_01,        // constant 0x93
        quest_02,        // constant 0x94
        quest_03,        // constant 0x95
        hu_talker,       // constant 0x96
        hu_quest_01,         // constant 0x97
        hu_quest_02,         // constant 0x98
        hu_quest_03,         // constant 0x99
        hu_enemy_demi_human_00,      // constant 0x9A
        hu_enemy_machine_00,         // constant 0x9B
        hu_nakama_tag,       // constant 0x9C
        hu_boss_main,        // constant 0x9D
        hu_quest_04,         // constant 0x9E
        hu_quest_05,         // constant 0x9F
        hu_quest_06,         // constant 0xA0
        hu_quest_07,         // constant 0xA1
        hu_quest_08,         // constant 0xA2
        hu_quest_09,         // constant 0xA3
        hu_quest_10,         // constant 0xA4
        hu_cabaret_yoasobi_w00,      // constant 0xA5
        hu_cabaret_yoasobi_w01,      // constant 0xA6
        hu_cabaret_yoasobi_m00,      // constant 0xA7
        hu_cabaret_yoasobi_m01,      // constant 0xA8
        hu_cabaret_yoasobi_m02,      // constant 0xA9
        hu_cabaret_yoasobi_m03,      // constant 0xAA
        hu_cabaret_yoasobi_m04,      // constant 0xAB
        num,         // constant 0xAC
    };
}
