[Settings]
input=y0
output=ylad

;Setting for converting from OOE games.
[FromOOESettings]
hact_csv_bin_path=E:\SteamLibrary\steamapps\common\Yakuza 3\data\hact\hact_csv.par.unpack\hact_csv\hact_csv.bin