using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace HActLib
{
    public enum Y0NodeIDs : uint
    {
        e_auth_element_particle = 2,
        e_auth_element_particle_fade = 3,
        e_auth_element_particle_opacity = 4,
        e_auth_element_ground_particle = 5,
        e_auth_element_fade = 6,
        e_auth_element_color_correction = 7,
        e_auth_element_blur = 8,
        e_auth_element_gradation = 9,
        e_auth_element_depth_of_field = 10,
        e_auth_element_picture = 11,
        e_auth_element_noise = 12,
        e_auth_element_shadow_display_control = 15,
        e_auth_element_shadow_drawing_area_correction = 16,
        e_auth_element_stage_shadow_control = 17,
        e_auth_element_clip_plane_setting = 18,
        e_auth_element_eye_brightness_correction = 19,
        e_auth_element_wrinkle_blend_ratio = 20,
        e_auth_element_mouth_brightness_correction = 21,
        e_auth_element_expression_target = 22,
        e_auth_element_draw_off = 23,
        e_auth_element_stage_object = 24,
        e_auth_element_weapon_trail = 25,
        e_auth_element_trail = 26,
        e_auth_element_ghost_afterimage = 27,
        e_auth_element_blood = 31,
        e_auth_element_damage = 32,
        e_auth_element_sound = 33,
        e_auth_element_hact_input = 34,
        e_auth_element_character_parallel_light_source = 35,
        e_auth_element_hact_end = 37,
        e_auth_element_hact_branching = 38,
        e_auth_element_tone_mapping = 39,
        e_auth_element_tone_mapping_upper_and_lower = 40,
        e_auth_element_stage_parallel_light_source = 41,
        e_auth_element_stage_parallel_ssao = 42,
        e_auth_element_point_light_source = 43,
        e_auth_element_hact_input_barrage = 44,
        e_auth_element_pseudo_point_light_source_cone = 45,
        //Matches up to this point on all OE games
        //somewhere between 47-69, they killed off two nodes
        e_auth_element_hact2d = 46,
        e_auth_element_hact_scenario_flag = 47,
        e_auth_element_hact_end_state_change = 48,
        e_auth_element_heat_change = 49,
        e_auth_element_snow = 50,
        e_auth_element_health_check = 51,
        e_auth_element_point_light_source_switching = 52,
        e_auth_element_character_point_light_disable = 53,
        e_auth_element_path_animation = 55,
        e_auth_element_glass_water = 56,
        e_auth_element_glass_water_parameter_change = 57,
        e_auth_element_look_to = 60,
        e_auth_element_look_to_position = 61,
        e_auth_element_path_adjustment = 62,
        e_auth_element_shoes_off = 64,
        e_auth_element_pseudo_point_light_source_specular = 65,
        e_auth_element_movie_texture = 66,
        e_auth_element_rim_light_scale = 67,
        e_auth_element_hact_no_representation = 68,
        e_auth_element_fresnel_coefficient = 69,
        e_auth_element_hact_hide = 70,
        e_auth_element_hact_stop_end = 71,
        e_auth_element_character_parallel_light_animation = 72,
        e_auth_element_texture_overlay = 73,
        e_auth_element_cross_fade = 74,
        e_auth_element_crowd_billboard = 75,
        e_auth_element_cloth_control_reset = 77,
        e_auth_element_hact_general_purpose_timer = 78,
        e_auth_element_light_scatter = 79,
        e_auth_element_controller_vibration = 80,
        e_auth_element_person_caption = 81,
        e_auth_element_remove_all_reactors = 83,
        e_auth_element_force_stage_lod = 84,
        e_auth_element_light_shaft = 85,
        e_auth_element_shock_wave = 86,
        e_auth_element_node_scale = 89,
        e_auth_element_hact_continuous_playback = 91,
        e_auth_element_crowd_billboard_people_list = 92,
        e_auth_element_cloth_weight = 93,
        e_auth_element_disable_hact_effect = 94,
        e_auth_element_subtitles = 95,
        e_auth_element_texture_change = 98,
        e_auth_element_2d_fade = 99,
        e_auth_element_body_flash = 100,
        e_auth_element_reactor_fade_disable = 102,
        e_auth_element_subtractive_point_light = 105,
        e_auth_element_stage_parallel_light_animation = 106,
        e_auth_element_character_parallel_light_source_offset = 107,
        e_auth_element_character_light_source = 108,
        e_auth_element_depth_of_field2 = 109,
        e_auth_element_draw_transparent_after_post_process = 113,
        e_auth_element_sss_range = 114,
        e_auth_element_adjust_sss_shadow_side_appearance = 115,
        e_auth_element_slow_sound_production = 116,
        e_auth_element_ui = 117,
        e_auth_element_color_correction_offset = 118,
        e_auth_element_cut_wound = 119,
        e_auth_element_add_body_damage = 120,
        e_auth_element_ink_filter_new = 121,
        e_auth_element_ink_filter_new_parameters = 122,
        e_auth_element_fix_hair = 128,
        e_auth_element_rain = 130,
        e_auth_element_animated_subtitles = 131,
        e_auth_element_fixed_camera = 132,
        e_auth_element_stream_playback = 135,
        e_auth_element_rainy_road_surface_reflection_parameter = 136,
        e_auth_element_hact_hand_pattern_change_weapon = 137,
        e_auth_element_sea_parameters = 138,
        e_auth_element_stage_draw_off = 140,
        e_auth_element_character_force_lod = 142,
        e_auth_element_hact_disable_setting = 143,
        e_auth_element_use_depth_buffer_for_shadow_blur = 144,
        e_auth_element_chromatic_aberration = 145,
        e_auth_element_tongue_finetuning = 146,
        e_auth_element_confetti = 148,
        e_auth_element_discoball3_parameter_control = 149,
        e_auth_element_extended_single_picture = 150,
        e_auth_element_pan_camera = 151,
        e_auth_element_catfight_damage = 153,
        e_auth_element_ink_filter_paper_cutout_movement_control = 157,
        e_auth_element_third_button_press = 159,
        e_auth_element_mesuking_subtitles = 160,
    }
}
