using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace HActLib
{
    public enum Y5NodeIDs : uint
    {
        e_auth_element_particle = 2,
        e_auth_element_particle_opacity = 4,
        e_auth_element_ground_particle = 5,
        e_auth_element_fade = 6,
        e_auth_element_color_correction = 7,
        e_auth_element_blur = 8,
        e_auth_element_gradation = 9,
        e_auth_element_depth_of_field = 10,
        e_auth_element_picture = 11,
        e_auth_element_noise = 12,
        e_auth_element_shadow_display_control = 15,
        e_auth_element_shadow_drawing_area_correction = 16,
        e_auth_element_stage_shadow_control = 17,
        e_auth_element_clip_plane_setting = 18,
        e_auth_element_eye_brightness_correction = 19,
        e_auth_element_wrinkle_blend_ratio = 20,
        e_auth_element_mouth_brightness_correction = 21,
        e_auth_element_face_expression = 22,
        e_auth_element_draw_off = 23,
        e_auth_element_stage_object = 24,
        e_auth_element_trail = 26,
        e_auth_element_ghost_afterimage = 27,
        e_auth_element_body_flash = 28,
        e_auth_element_blood = 31,
        e_auth_element_damage = 32,
        e_auth_element_sound = 33,
        e_auth_element_hact_input = 34,
        e_auth_element_character_parallel_light_source = 35,
        e_auth_element_hact_end = 37,
        e_auth_element_hact_branching = 38,
        e_auth_element_tone_mapping = 39,
        e_auth_element_tone_mapping_upper_and_lower = 40,
        e_auth_element_stage_parallel_light_source = 41,
        e_auth_element_stage_parallel_ssao = 42,
        e_auth_element_point_light_source = 43,
        e_auth_element_hact_input_barrage = 44,
        e_auth_element_pseudo_point_light_source_cone = 45,
        e_auth_element_counterattack_extremity = 46,
        e_auth_element_hact2d = 47,
        e_auth_element_hact_scenario_flag = 48,
        e_auth_element_hact_end_state_change = 49,
        e_auth_element_heat_change = 50,
        e_auth_element_snow = 51,
        e_auth_element_hact_health_condition = 52,
        e_auth_element_point_light_source_switching = 53,
        e_auth_element_character_point_light_disable = 54,
        e_auth_element_facial_expression = 55,
        e_auth_element_snow_on_body = 56,
        e_auth_element_glass_water = 57,
        e_auth_element_glass_water_parameter_change = 58,
        e_auth_element_render_texture= 59,
        e_auth_element_look_to = 62,
        e_auth_element_path_adjustment = 64,
        e_auth_element_shoes_off = 66,
        e_auth_element_pseudo_point_light_source_specular = 67,
        e_auth_element_movie_texture = 68,
        e_auth_element_rim_light = 69,
        e_auth_element_look_to_position = 63,
        e_auth_element_hact_hide = 70,
        e_auth_element_fresnel_coefficient = 71,
        e_auth_element_use_multiple_shadows = 72,
        e_auth_element_character_parallel_light_animation = 74,
        e_auth_element_hact_stop_end = 73,
        e_auth_element_character_model_change = 75,
        e_auth_element_cross_fade = 76,
        e_auth_element_crowd_billboard = 77,
        e_auth_element_hact_general_purpose_timer = 80,
        e_auth_element_light_scatter = 81,
        e_auth_element_controller_vibration = 82,
        e_auth_element_person_caption = 83,
        e_auth_element_stage_layout = 84,
        e_auth_element_remove_all_reactors = 85,
        e_auth_element_force_stage_lod = 86,
        e_auth_element_light_shaft = 87,
        e_auth_element_mist = 89,
        e_auth_element_glass_water_overflow = 90,
        e_auth_element_hact_continuous_playback = 93,
        e_auth_element_cloth_weight = 95,
        e_auth_element_disable_hact_effect = 96,
        e_auth_element_subtitles = 97,
        e_auth_element_hact_fighter_condition = 98,
        e_auth_element_texture_change = 100,
        e_auth_element_2d_fade = 101,
        e_auth_element_character_caption = 92,
        e_auth_element_crowd_billboard_people_list = 94,
        e_auth_element_hact_skill_condition = 103,
        e_auth_element_reactor_fade_disable = 104,
        e_auth_element_hact_generic_condition = 105,
        e_auth_element_hact_script = 106,
    }
}
