using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace HActLib
{

    public enum DEFaceTarget : uint
    {
        invalid,         // constant 0x0
        a_l,         // constant 0x1
        a_r,         // constant 0x2
        i_l,         // constant 0x3
        i_r,         // constant 0x4
        u_l,         // constant 0x5
        u_r,         // constant 0x6
        e_l,         // constant 0x7
        e_r,         // constant 0x8
        o_l,         // constant 0x9
        o_r,         // constant 0xA
        open_a_l,        // constant 0xB
        open_a_r,        // constant 0xC
        open_i_l,        // constant 0xD
        open_i_r,        // constant 0xE
        open_u_l,        // constant 0xF
        open_u_r,        // constant 0x10
        open_e_l,        // constant 0x11
        open_e_r,        // constant 0x12
        open_o_l,        // constant 0x13
        open_o_r,        // constant 0x14
        eye_anger_l,         // constant 0x15
        eye_anger_r,         // constant 0x16
        eye_pain_l,      // constant 0x17
        eye_pain_r,      // constant 0x18
        eye_sad_l,       // constant 0x19
        eye_sad_r,       // constant 0x1A
        eye_sup_l,       // constant 0x1B
        eye_sup_r,       // constant 0x1C
        eye_open_l,      // constant 0x1D
        eye_open_r,      // constant 0x1E
        eye_close_l,         // constant 0x1F
        eye_close_r,         // constant 0x20
        eye_up_l,        // constant 0x21
        eye_up_r,        // constant 0x22
        eye_down_l,      // constant 0x23
        eye_down_r,      // constant 0x24
        eye_left_l,      // constant 0x25
        eye_left_r,      // constant 0x26
        eye_right_l,         // constant 0x27
        eye_right_r,         // constant 0x28
        joy_l,       // constant 0x29
        jaw_down,        // constant 0x2A
        jaw_left,        // constant 0x2B
        jaw_right,       // constant 0x2C
        jaw_front,       // constant 0x2D
        joy_r,       // constant 0x2E
        lip_up,      // constant 0x2F
        lip_down,        // constant 0x30
        lip_left,        // constant 0x31
        lip_right,       // constant 0x32
        lip_bp,      // constant 0x33
        lip_gi,      // constant 0x34
        lip_woo,         // constant 0x35
        lipside_up_l,        // constant 0x36
        lipside_up_r,        // constant 0x37
        lipside_down_l,      // constant 0x38
        lipside_down_r,      // constant 0x39
        lipside_center_l,        // constant 0x3A
        lipside_center_r,        // constant 0x3B
        lipside_wide_l,      // constant 0x3C
        lipside_wide_r,      // constant 0x3D
        lip_gin,         // constant 0x3E
        liptwist_left,       // constant 0x3F
        liptwist_right,      // constant 0x40
        eyebrow_up_l,        // constant 0x41
        eyebrow_up_r,        // constant 0x42
        eyebrow_down_l,      // constant 0x43
        eyebrow_down_r,      // constant 0x44
        eyebrow_open_l,      // constant 0x45
        eyebrow_open_r,      // constant 0x46
        eyebrow_close_l,         // constant 0x47
        eyebrow_close_r,         // constant 0x48
        cheek_up_l,      // constant 0x49
        cheek_up_r,      // constant 0x4A
        liptop_up,       // constant 0x4B
        liptop_down,         // constant 0x4C
        liptop_left,         // constant 0x4D
        liptop_right,        // constant 0x4E
        lipbtm_up,       // constant 0x4F
        lipbtm_down,         // constant 0x50
        lipbtm_left,         // constant 0x51
        lipbtm_right,        // constant 0x52
        lip_sh,      // constant 0x53
        liptop_front,        // constant 0x54
        liptop_back,         // constant 0x55
        lipbtm_front,        // constant 0x56
        lipbtm_back,         // constant 0x57
        jaw_up,      // constant 0x58
        jaw_back,        // constant 0x59
        a_l_be,      // constant 0x5A
        a_r_be,      // constant 0x5B
        i_l_be,      // constant 0x5C
        i_r_be,      // constant 0x5D
        u_l_be,      // constant 0x5E
        u_r_be,      // constant 0x5F
        e_l_be,      // constant 0x60
        e_r_be,      // constant 0x61
        o_l_be,      // constant 0x62
        o_r_be,      // constant 0x63
        open_a_l_be,         // constant 0x64
        open_a_r_be,         // constant 0x65
        open_i_l_be,         // constant 0x66
        open_i_r_be,         // constant 0x67
        open_u_l_be,         // constant 0x68
        open_u_r_be,         // constant 0x69
        open_e_l_be,         // constant 0x6A
        open_e_r_be,         // constant 0x6B
        open_o_l_be,         // constant 0x6C
        open_o_r_be,         // constant 0x6D
        lip_sh_be,       // constant 0x6E
        lip_bp_be,       // constant 0x6F
        anger02,         // constant 0x70
        anger03,         // constant 0x71
        doubt01,         // constant 0x72
        hatred01,        // constant 0x73
        joy02,       // constant 0x74
        joy03,       // constant 0x75
        pain02,      // constant 0x76
        scared01,        // constant 0x77
        scream01,        // constant 0x78
        serious01,       // constant 0x79
        surprise02,      // constant 0x7A
        tired01,         // constant 0x7B
        eye_anger02,         // constant 0x7C
        eye_anger03,         // constant 0x7D
        eye_hatred01,        // constant 0x7E
        eye_joy02,       // constant 0x7F
        eye_joy03,       // constant 0x80
        eye_pain02,      // constant 0x81
        eye_scared01,        // constant 0x82
        eye_scream01,        // constant 0x83
        eye_tired01,         // constant 0x84
        extra,       // constant 0x85
        special01,       // constant 0x86
        special02,       // constant 0x87
        special03,       // constant 0x88
        special04,       // constant 0x89
        special05,       // constant 0x8A
        special06,       // constant 0x8B
        param0__0,       // constant 0x8C
        param0__1,       // constant 0x8D
        param1__0,       // constant 0x8E
        param1__1,       // constant 0x8F
        param3__0,       // constant 0x90
        param3__1,       // constant 0x91
        param5__0,       // constant 0x92
        param5__1,       // constant 0x93
        param7__0,       // constant 0x94
        param7__1,       // constant 0x95
        headlip,         // constant 0x96
        non,         // constant 0x97
    }

}
